//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.26 at 03:23:27 PM BST 
//


package com.performance.jaxbs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "bridgepa-data")
public class BridgePerformanceData {

    protected List<Report> report;
  
    public List<Report> getReport() {
        if (report == null) {
        	report = new ArrayList<Report>();
        }
        return this.report;
    }
	public void setReport(List<Report> report) {
		this.report = report;
	}      

}
