//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.26 at 03:23:27 PM BST 
//


package com.performance.jaxbs;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


        @XmlRootElement(name="report-details")
        public class ReportDetails {
        	
        	protected String gateNumber;
        	protected String size;
            protected String direction;
            protected String vehicleType;
            protected String vrn;
            protected String crossingDateAndTime;
            
            @XmlElement
			public String getGateNumber() {
				return gateNumber;
			}
			public void setGateNumber(String string) {
				this.gateNumber = string;
			}
			
			@XmlElement
			public String getSize() {
				return size;
			}			
			public void setSize(String size) {
				this.size = size;
			}
			
			@XmlElement
			public String getDirection() {
				return direction;
			}
			public void setDirection(String direction) {
				this.direction = direction;
			}
			
			@XmlElement
			public String getVehicleType() {
				return vehicleType;
			}
			public void setVehicleType(String vehicleType) {
				this.vehicleType = vehicleType;
			}
			
			@XmlElement
			public String getVrn() {
				return vrn;
			}
			public void setVrn(String vrn) {
				this.vrn = vrn;
			}
			
			@XmlElement
			public String getCrossingDateAndTime() {
				return crossingDateAndTime;
			}
			public void setCrossingDateAndTime(String crossingDateAndTime) {
				this.crossingDateAndTime = crossingDateAndTime;
			}
			        
        }

  


